/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPolicies"];
        put: operations["updatePolicies"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordActions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspection-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSchedules"];
        put?: never;
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBundles"];
        put?: never;
        /**
         * 포장 생성
         * @description 배정된 칸에 새로운 포장을 추가한다. 허용량(`capacity`)을 초과하면 422 `CAPACITY_EXCEEDED`가 반환된다. 데모 시나리오에서는 2층 A칸(`slotIndex` 0)만 설명용으로 허용량이 3으로 제한돼 있다.
         */
        post: operations["createBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/bundles/{bundleId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/roles/floor-manager": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promoteFloorManager"];
        delete: operations["demoteFloorManager"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/seed/fridge-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 데모 데이터 초기화
         * @description 관리자가 냉장고 데모 데이터를 초기화한다.
         */
        post: operations["seedFridgeDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/reallocations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/reallocations/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markRead"];
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markAllRead"];
        trace?: never;
    };
    "/notifications/preferences/{kindCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updatePreference"];
        trace?: never;
    };
    "/fridge/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch: operations["updateItem"];
        trace?: never;
    };
    "/fridge/inspections/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["cancelSession"];
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/fridge/inspection-schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch: operations["updateSchedule"];
        trace?: never;
    };
    "/fridge/bundles/{bundleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBundle"];
        put?: never;
        post?: never;
        delete: operations["deleteBundle"];
        options?: never;
        head?: never;
        patch: operations["updateBundle"];
        trace?: never;
    };
    "/admin/users/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUserStatus"];
        trace?: never;
    };
    "/admin/fridge/compartments/{compartmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 냉장고 칸 설정 수정
         * @description 관리자가 특정 칸의 허용량과 상태를 조정한다.
         */
        patch: operations["updateCompartment"];
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspection-schedules/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNextSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/compartments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 냉장고 칸 메타데이터 조회
         * @description 관리자가 층별 칸 정보를 확인한다.
         */
        get: operations["listCompartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/bundles/deleted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeletedBundles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NotificationPolicy: {
            batchTime: string;
            /** Format: int32 */
            dailyLimit?: number;
            /** Format: int32 */
            ttlHours?: number;
        };
        PenaltyPolicy: {
            /** Format: int32 */
            limit?: number;
            template: string;
        };
        UpdateAdminPoliciesRequest: {
            notification: components["schemas"]["NotificationPolicy"];
            penalty: components["schemas"]["PenaltyPolicy"];
        };
        StartInspectionRequest: {
            /** Format: uuid */
            slotId: string;
            /** Format: uuid */
            scheduleId?: string;
        };
        FridgeBundleResponse: {
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            slotId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /** Format: int32 */
            labelNumber?: number;
            labelDisplay?: string;
            bundleName?: string;
            memo?: string;
            /** Format: uuid */
            ownerUserId?: string;
            ownerDisplayName?: string;
            ownerRoomNumber?: string;
            status?: string;
            freshness?: string;
            /** Format: int32 */
            itemCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            removedAt?: string;
            items?: components["schemas"]["FridgeItemResponse"][];
        };
        FridgeItemResponse: {
            /** Format: uuid */
            itemId?: string;
            /** Format: uuid */
            bundleId?: string;
            name?: string;
            /** Format: date */
            expiryDate?: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
            freshness?: string;
            /** Format: date-time */
            lastInspectedAt?: string;
            updatedAfterInspection?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            removedAt?: string;
        };
        InspectionActionDetailResponse: {
            /** Format: int64 */
            actionId?: number;
            actionType?: string;
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            targetUserId?: string;
            /** Format: date-time */
            recordedAt?: string;
            /** Format: uuid */
            recordedBy?: string;
            recordedByLogin?: string;
            recordedByName?: string;
            note?: string;
            /** Format: uuid */
            correlationId?: string;
            roomNumber?: string;
            /** Format: int32 */
            personalNo?: number;
            targetName?: string;
            items?: components["schemas"]["InspectionActionItemResponse"][];
            penalties?: components["schemas"]["PenaltyHistoryResponse"][];
        };
        InspectionActionItemResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: uuid */
            fridgeItemId?: string;
            snapshotName?: string;
            /** Format: date */
            snapshotExpiresOn?: string;
            /** Format: int32 */
            quantityAtAction?: number;
            /** Format: uuid */
            correlationId?: string;
        };
        InspectionActionSummaryResponse: {
            action?: string;
            /** Format: int32 */
            count?: number;
        };
        InspectionSessionResponse: {
            /** Format: uuid */
            sessionId?: string;
            /** Format: uuid */
            slotId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /** Format: int32 */
            floorNo?: number;
            floorCode?: string;
            status?: string;
            /** Format: uuid */
            startedBy?: string;
            startedByLogin?: string;
            startedByName?: string;
            startedByRoomNumber?: string;
            /** Format: int32 */
            startedByPersonalNo?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            bundles?: components["schemas"]["FridgeBundleResponse"][];
            summary?: components["schemas"]["InspectionActionSummaryResponse"][];
            actions?: components["schemas"]["InspectionActionDetailResponse"][];
            notes?: string;
            /** Format: int32 */
            initialBundleCount?: number;
            /** Format: int32 */
            totalBundleCount?: number;
        };
        PenaltyHistoryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            points?: number;
            reason?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: uuid */
            correlationId?: string;
        };
        SubmitInspectionRequest: {
            notes?: string;
        };
        InspectionActionEntryRequest: {
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            itemId?: string;
            action: string;
            note?: string;
        };
        InspectionActionRequest: {
            actions: components["schemas"]["InspectionActionEntryRequest"][];
        };
        CreateInspectionScheduleRequest: {
            /** Format: date-time */
            scheduledAt: string;
            title?: string;
            notes?: string;
            /** Format: uuid */
            fridgeCompartmentId: string;
        };
        InspectionScheduleResponse: {
            /** Format: uuid */
            scheduleId?: string;
            /** Format: date-time */
            scheduledAt?: string;
            title?: string;
            notes?: string;
            status?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: uuid */
            inspectionSessionId?: string;
            /** Format: uuid */
            fridgeCompartmentId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLetter?: string;
            /** Format: int32 */
            floorNo?: number;
            floorCode?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateBundleItemInput: {
            name: string;
            /** Format: date */
            expiryDate: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
        };
        CreateBundleRequest: {
            /** Format: uuid */
            slotId: string;
            bundleName: string;
            memo?: string;
            items: components["schemas"]["CreateBundleItemInput"][];
        };
        CreateBundleResponse: {
            bundle?: components["schemas"]["FridgeBundleResponse"];
        };
        AddItemRequest: {
            name: string;
            /** Format: date */
            expiryDate: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
        };
        RefreshRequest: {
            refreshToken: string;
            deviceId: string;
        };
        LoginResponse: {
            tokens?: components["schemas"]["TokenPairResponse"];
            user?: components["schemas"]["UserProfileResponse"];
        };
        RoomAssignmentResponse: {
            /** Format: uuid */
            roomId?: string;
            /** Format: int32 */
            floor?: number;
            roomNumber?: string;
            /** Format: int32 */
            personalNo?: number;
            /** Format: date-time */
            assignedAt?: string;
            floorCode?: string;
        };
        TokenPairResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
            refreshToken?: string;
            /** Format: int64 */
            refreshExpiresIn?: number;
            /** Format: date-time */
            issuedAt?: string;
        };
        UserProfileResponse: {
            /** Format: uuid */
            userId?: string;
            loginId?: string;
            displayName?: string;
            email?: string;
            roles?: string[];
            primaryRoom?: components["schemas"]["RoomAssignmentResponse"];
            isFloorManager?: boolean;
            isAdmin?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            loginId: string;
            password: string;
            deviceId: string;
        };
        SeedResponse: {
            message?: string;
            /** Format: date-time */
            executedAt?: string;
        };
        ReallocationPreviewRequest: {
            /** Format: int32 */
            floor?: number;
        };
        CompartmentAllocationView: {
            /** Format: uuid */
            compartmentId?: string;
            /** Format: uuid */
            fridgeUnitId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /** @enum {string} */
            compartmentType?: "CHILL" | "FREEZE";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "REPORTED" | "RETIRED";
            locked?: boolean;
            currentRoomIds?: string[];
            recommendedRoomIds?: string[];
            warnings?: string[];
        };
        ReallocationPreviewResponse: {
            /** Format: int32 */
            floor?: number;
            rooms?: components["schemas"]["RoomSummary"][];
            allocations?: components["schemas"]["CompartmentAllocationView"][];
            /** Format: int32 */
            chillCompartmentCount?: number;
        };
        RoomSummary: {
            /** Format: uuid */
            roomId?: string;
            roomNumber?: string;
            roomType?: string;
            /** Format: int32 */
            floor?: number;
        };
        CompartmentAllocationInput: {
            /** Format: uuid */
            compartmentId: string;
            roomIds: string[];
        };
        ReallocationApplyRequest: {
            /** Format: int32 */
            floor?: number;
            allocations: components["schemas"]["CompartmentAllocationInput"][];
        };
        ReallocationApplyResponse: {
            /** Format: int32 */
            floor?: number;
            /** Format: int32 */
            affectedCompartments?: number;
            /** Format: int32 */
            releasedAssignments?: number;
            /** Format: int32 */
            createdAssignments?: number;
            /** Format: date-time */
            appliedAt?: string;
        };
        UpdateNotificationPreferenceRequest: {
            enabled: boolean;
            allowBackground: boolean;
        };
        NotificationPreferenceItemResponse: {
            kindCode?: string;
            displayName?: string;
            description?: string;
            enabled?: boolean;
            allowBackground?: boolean;
        };
        UpdateItemRequest: {
            name?: string;
            /** Format: date */
            expiryDate?: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
            /** Format: date-time */
            removedAt?: string;
        };
        InspectionActionMutationRequest: {
            /** Format: int64 */
            actionId?: number;
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            itemId?: string;
            action: string;
            note?: string;
        };
        UpdateInspectionSessionRequest: {
            notes?: string;
            mutations?: components["schemas"]["InspectionActionMutationRequest"][];
            deleteActionIds?: number[];
        };
        UpdateInspectionScheduleRequest: {
            /** Format: date-time */
            scheduledAt?: string;
            title?: string;
            notes?: string;
            status?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: uuid */
            inspectionSessionId?: string;
            detachInspectionSession?: boolean;
            /** Format: uuid */
            fridgeCompartmentId?: string;
        };
        UpdateBundleRequest: {
            bundleName?: string;
            memo?: string;
            /** Format: date-time */
            removedAt?: string;
        };
        UpdateUserStatusRequest: {
            status: string;
        };
        UpdateCompartmentConfigRequest: {
            /** Format: int32 */
            maxBundleCount?: number;
            status?: string;
        };
        FridgeSlotResponse: {
            /** Format: uuid */
            slotId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLetter?: string;
            /** Format: int32 */
            floorNo?: number;
            floorCode?: string;
            compartmentType?: string;
            resourceStatus?: string;
            /**
             * @description Computed status that indicates whether the compartment is ACTIVE, LOCKED, or currently IN_INSPECTION.
             * @enum {string}
             */
            slotStatus?: "ACTIVE" | "LOCKED" | "IN_INSPECTION";
            locked?: boolean;
            /** Format: date-time */
            lockedUntil?: string;
            /** Format: int32 */
            capacity?: number;
            displayName?: string;
            /** Format: int32 */
            occupiedCount?: number;
        };
        HealthResponse: {
            status?: string;
            timestamp?: string;
        };
        NotificationItemResponse: {
            /** Format: uuid */
            id?: string;
            kindCode?: string;
            title?: string;
            body?: string;
            state?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            readAt?: string;
            /** Format: date-time */
            ttlAt?: string;
            /** Format: uuid */
            correlationId?: string;
            metadata?: {
                [key: string]: Record<string, never>;
            };
        };
        NotificationListResponse: {
            items?: components["schemas"]["NotificationItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            unreadCount?: number;
        };
        NotificationPreferenceResponse: {
            items?: components["schemas"]["NotificationPreferenceItemResponse"][];
        };
        FridgeSlotListResponse: {
            items?: components["schemas"]["FridgeSlotResponse"][];
            /** Format: int64 */
            totalCount?: number;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        BundleListResponse: {
            items?: components["schemas"]["FridgeBundleSummaryResponse"][];
            /** Format: int64 */
            totalCount?: number;
        };
        FridgeBundleSummaryResponse: {
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            slotId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /** Format: int32 */
            labelNumber?: number;
            labelDisplay?: string;
            bundleName?: string;
            memo?: string;
            /** Format: uuid */
            ownerUserId?: string;
            ownerDisplayName?: string;
            ownerRoomNumber?: string;
            status?: string;
            freshness?: string;
            /** Format: int32 */
            itemCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            removedAt?: string;
        };
        AdminUsersResponse: {
            items?: components["schemas"]["User"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            availableFloors?: number[];
        };
        User: {
            id?: string;
            name?: string;
            room?: string;
            /** Format: int32 */
            floor?: number;
            roomCode?: string;
            /** Format: int32 */
            personalNo?: number;
            role?: string;
            roles?: string[];
            status?: string;
            lastLogin?: string;
            /** Format: int32 */
            penalties?: number;
        };
        AdminPoliciesResponse: {
            notification?: components["schemas"]["NotificationPolicy"];
            penalty?: components["schemas"]["PenaltyPolicy"];
        };
        AdminDashboardResponse: {
            summary?: components["schemas"]["SummaryCard"][];
            timeline?: components["schemas"]["TimelineEvent"][];
            quickActions?: components["schemas"]["QuickAction"][];
        };
        QuickAction: {
            id?: string;
            title?: string;
            description?: string;
            href?: string;
            icon?: string;
        };
        SummaryCard: {
            id?: string;
            label?: string;
            value?: string;
            description?: string;
        };
        TimelineEvent: {
            id?: string;
            time?: string;
            title?: string;
            detail?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminPoliciesResponse"];
                };
            };
        };
    };
    updatePolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdminPoliciesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSessions: {
        parameters: {
            query?: {
                slotId?: string;
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"][];
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartInspectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
        };
    };
    submitSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubmitInspectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
        };
    };
    recordActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectionActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
        };
    };
    listSchedules: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"][];
                };
            };
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInspectionScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"];
                };
            };
        };
    };
    getBundles: {
        parameters: {
            query?: {
                slotId?: string;
                owner?: string;
                status?: string;
                search?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BundleListResponse"];
                };
            };
        };
    };
    createBundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBundleRequest"];
            };
        };
        responses: {
            /** @description 포장 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateBundleResponse"];
                };
            };
            /** @description 허용량 초과 – detail 값이 `CAPACITY_EXCEEDED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateBundleResponse"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeItemResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    promoteFloorManager: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    demoteFloorManager: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    seedFridgeDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초기화 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeedResponse"];
                };
            };
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeedResponse"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReallocationPreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReallocationPreviewResponse"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReallocationApplyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReallocationApplyResponse"];
                };
            };
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePreference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kindCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationPreferenceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationPreferenceItemResponse"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeItemResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
        };
    };
    cancelSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInspectionSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInspectionScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"];
                };
            };
        };
    };
    getBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeBundleResponse"];
                };
            };
        };
    };
    deleteBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBundleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeBundleResponse"];
                };
            };
        };
    };
    updateUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCompartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compartmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompartmentConfigRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            /** @description 대상 칸 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            /** @description 검사 세션 진행 중 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            /** @description 현재 활성 포장 수보다 낮은 용량으로 설정 시 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query?: {
                state?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationListResponse"];
                };
            };
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationPreferenceResponse"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getSlots: {
        parameters: {
            query?: {
                floor?: number;
                view?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotListResponse"];
                };
            };
        };
    };
    getActiveSession: {
        parameters: {
            query?: {
                floor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
        };
    };
    getNextSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"];
                };
            };
        };
    };
    getUsers: {
        parameters: {
            query?: {
                status?: string;
                floor?: string;
                search?: string;
                floorManagerOnly?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminUsersResponse"];
                };
            };
        };
    };
    listCompartments: {
        parameters: {
            query?: {
                floor?: number;
                view?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"][];
                };
            };
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"][];
                };
            };
        };
    };
    getDeletedBundles: {
        parameters: {
            query?: {
                since?: string;
                slotId?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BundleListResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminDashboardResponse"];
                };
            };
        };
    };
}
