/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPolicies"];
        put: operations["updatePolicies"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordActions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspection-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSchedules"];
        put?: never;
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBundles"];
        put?: never;
        /**
         * 포장 생성
         * @description 배정된 칸에 새로운 포장을 추가한다. 허용량(`capacity`)을 초과하면 422 `CAPACITY_EXCEEDED`가 반환된다.
         */
        post: operations["createBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/bundles/{bundleId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Post-MVP 토큰 인증 후보 계약. MVP 세션 인증에서는 호출하거나 구현하지 않는다. */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 현재 서버 세션을 무효화하고 세션 쿠키를 만료시킨다. 이미 세션이 없거나 만료된 경우에도 성공으로 처리한다. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 자격 증명을 검증하고 서버 세션을 생성한다. 성공 시 세션 쿠키와 현재 사용자 프로필을 한 번의 응답으로 반환한다. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/seed/fridge-demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 데모 데이터 초기화
         * @description 관리자가 냉장고 데모 데이터를 초기화한다.
         */
        post: operations["seedFridgeDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/reallocations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/reallocations/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markRead"];
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["markAllRead"];
        trace?: never;
    };
    "/notifications/preferences/{kindCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updatePreference"];
        trace?: never;
    };
    "/fridge/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch: operations["updateItem"];
        trace?: never;
    };
    "/fridge/inspections/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["cancelSession"];
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/fridge/inspection-schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch: operations["updateSchedule"];
        trace?: never;
    };
    "/fridge/bundles/{bundleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBundle"];
        put?: never;
        post?: never;
        delete: operations["deleteBundle"];
        options?: never;
        head?: never;
        patch: operations["updateBundle"];
        trace?: never;
    };
    "/admin/users/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateUserStatus"];
        trace?: never;
    };
    "/admin/fridge/compartments/{compartmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 냉장고 칸 설정 수정
         * @description 관리자가 특정 칸의 허용량과 상태를 조정한다.
         */
        patch: operations["updateCompartment"];
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPreferences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CSRF 토큰 발급
         * @description SPA가 로그인, 로그아웃과 상태 변경 요청 헤더에 전달할 CSRF 토큰을 발급한다.
         */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 접근 가능한 냉장고 칸 조회
         * @description 인증된 일반 거주자의 현재 거주 호실에 활성 배정된 냉장고 칸을 조회한다. 배정된 칸은 운영 상태와 관계없이 조회하므로 RETIRED 칸도 상태와 함께 반환될 수 있다. 결과는 floorNo, fridgeId, displayName, slotId 오름차순으로 정렬한다.
         */
        get: operations["getSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getActiveSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspection-schedules/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNextSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFridgeOwnershipIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/compartments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 냉장고 칸 메타데이터 조회
         * @description 관리자가 층별 칸 정보를 확인한다.
         */
        get: operations["listCompartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/fridge/bundles/deleted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeletedBundles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/actions/{actionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteAction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fridge/inspections/{sessionId}/notifications/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendInspectionNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CsrfTokenResponse: {
            /** @example X-CSRF-TOKEN */
            headerName: string;
            /** @example _csrf */
            parameterName: string;
            token: string;
        };
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            code?: string;
            errors?: {
                [key: string]: string[];
            };
            properties?: {
                [key: string]: unknown;
            };
        };
        NotificationPolicy: {
            batchTime: string;
            /** Format: int32 */
            dailyLimit?: number;
            /** Format: int32 */
            ttlHours?: number;
        };
        PenaltyPolicy: {
            /** Format: int32 */
            limit?: number;
            template: string;
        };
        UpdateAdminPoliciesRequest: {
            notification: components["schemas"]["NotificationPolicy"];
            penalty: components["schemas"]["PenaltyPolicy"];
        };
        StartInspectionRequest: {
            /** Format: uuid */
            slotId: string;
            /** Format: uuid */
            scheduleId?: string;
        };
        FridgeBundleResponse: {
            /**
             * Format: uuid
             * @description 포장의 UUID 영속 식별자. 라벨 번호와 구분하며 API 및 이력 연결에 사용한다.
             */
            bundleId?: string;
            /** Format: uuid */
            slotId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /**
             * Format: int32
             * @description 동일 Slot 안에서 발급되는 사용자용 라벨 번호. 화면에서는 3자리로 표시한다.
             */
            labelNumber?: number;
            /** @description 현재 slotLabel과 3자리 labelNumber를 조합한 표시값. 영속 식별자나 유일성 기준으로 사용하지 않는다. */
            labelDisplay?: string;
            bundleName?: string;
            memo?: string;
            /** Format: uuid */
            ownerUserId?: string;
            ownerDisplayName?: string;
            ownerRoomNumber?: string;
            status?: string;
            freshness?: string;
            /** Format: int32 */
            itemCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            removedAt?: string;
            items?: components["schemas"]["FridgeItemResponse"][];
        };
        FridgeItemResponse: {
            /** Format: uuid */
            itemId?: string;
            /** Format: uuid */
            bundleId?: string;
            name?: string;
            /** Format: date */
            expiryDate?: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
            freshness?: string;
            /** Format: date-time */
            lastInspectedAt?: string;
            updatedAfterInspection?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            removedAt?: string;
        };
        InspectionActionDetailResponse: {
            /** Format: int64 */
            actionId?: number;
            actionType?: string;
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            targetUserId?: string;
            /** Format: date-time */
            recordedAt?: string;
            /** Format: uuid */
            recordedBy?: string;
            recordedByLogin?: string;
            recordedByName?: string;
            note?: string;
            /** Format: uuid */
            correlationId?: string;
            roomNumber?: string;
            /** Format: int32 */
            personalNo?: number;
            targetName?: string;
            items?: components["schemas"]["InspectionActionItemResponse"][];
            penalties?: components["schemas"]["PenaltyHistoryResponse"][];
        };
        InspectionActionItemResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: uuid */
            fridgeItemId?: string;
            snapshotName?: string;
            /** Format: date */
            snapshotExpiresOn?: string;
            /** Format: int32 */
            quantityAtAction?: number;
            /** Format: uuid */
            correlationId?: string;
        };
        InspectionActionSummaryResponse: {
            action?: string;
            /** Format: int32 */
            count?: number;
        };
        InspectionSessionResponse: {
            /** Format: uuid */
            sessionId?: string;
            /** Format: uuid */
            slotId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /** Format: int32 */
            floorNo?: number;
            floorCode?: string;
            status?: string;
            /** Format: uuid */
            startedBy?: string;
            startedByLogin?: string;
            startedByName?: string;
            startedByRoomNumber?: string;
            /** Format: int32 */
            startedByPersonalNo?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            bundles?: components["schemas"]["FridgeBundleResponse"][];
            summary?: components["schemas"]["InspectionActionSummaryResponse"][];
            actions?: components["schemas"]["InspectionActionDetailResponse"][];
            notes?: string;
            /** Format: int32 */
            initialBundleCount?: number;
            /** Format: int32 */
            totalBundleCount?: number;
        };
        PenaltyHistoryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            points?: number;
            reason?: string;
            /** Format: date-time */
            issuedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: uuid */
            correlationId?: string;
        };
        SubmitInspectionRequest: {
            notes?: string;
        };
        InspectionActionEntryRequest: {
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            itemId?: string;
            action: string;
            note?: string;
        };
        InspectionActionRequest: {
            actions: components["schemas"]["InspectionActionEntryRequest"][];
        };
        CreateInspectionScheduleRequest: {
            /** Format: date-time */
            scheduledAt: string;
            title?: string;
            notes?: string;
            /** Format: uuid */
            fridgeCompartmentId: string;
        };
        InspectionScheduleResponse: {
            /** Format: uuid */
            scheduleId?: string;
            /** Format: date-time */
            scheduledAt?: string;
            title?: string;
            notes?: string;
            status?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: uuid */
            inspectionSessionId?: string;
            /** Format: uuid */
            fridgeCompartmentId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLetter?: string;
            /** Format: int32 */
            floorNo?: number;
            floorCode?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateBundleItemInput: {
            name: string;
            /** Format: date */
            expiryDate: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
        };
        CreateBundleRequest: {
            /** Format: uuid */
            slotId: string;
            bundleName: string;
            memo?: string;
            items: components["schemas"]["CreateBundleItemInput"][];
        };
        CreateBundleResponse: {
            bundle?: components["schemas"]["FridgeBundleResponse"];
        };
        AddItemRequest: {
            name: string;
            /** Format: date */
            expiryDate: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
        };
        RefreshRequest: {
            refreshToken: string;
            deviceId: string;
        };
        LoginResponse: {
            tokens?: components["schemas"]["TokenPairResponse"];
            user?: components["schemas"]["UserProfileResponse"];
        };
        RoomAssignmentResponse: {
            /** Format: uuid */
            roomId: string;
            /**
             * Format: int32
             * @description 호실 번호 문자열에서 파싱하지 않는 구조화된 층 번호
             */
            floorNo: number;
            /** @description 사용자에게 표시하는 호실 표기. 층 판정이나 정렬을 위해 문자열을 파싱하지 않는다. */
            roomNumber: string;
            /** Format: int32 */
            personalNo?: number;
            /** Format: date-time */
            assignedAt?: string;
            floorCode?: string;
        };
        TokenPairResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
            refreshToken?: string;
            /** Format: int64 */
            refreshExpiresIn?: number;
            /** Format: date-time */
            issuedAt?: string;
        };
        UserProfileResponse: {
            /** Format: uuid */
            userId?: string;
            loginId?: string;
            displayName?: string;
            email?: string;
            /** @description 계정 자체에 부여된 권한. 거주 자격과 냉장고 관리 업무는 포함하지 않는다. */
            accountAuthorities?: string[];
            primaryRoom?: components["schemas"]["RoomAssignmentResponse"];
            /** @description 활성 거주 배정이 존재하는지 여부 */
            isResident?: boolean;
            /** @description 활성 SlotManagerAssignment가 하나 이상 존재하는지 여부 */
            isFridgeManager?: boolean;
            isAdmin?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            loginId: string;
            password: string;
        };
        SeedResponse: {
            message?: string;
            /** Format: date-time */
            executedAt?: string;
        };
        ReallocationPreviewRequest: {
            /** Format: int32 */
            floor?: number;
        };
        CompartmentAllocationView: {
            /** Format: uuid */
            compartmentId?: string;
            /** Format: uuid */
            fridgeUnitId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /** @enum {string} */
            compartmentType?: "CHILL" | "FREEZE";
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "REPORTED" | "RETIRED";
            locked?: boolean;
            currentRoomIds?: string[];
            recommendedRoomIds?: string[];
            warnings?: string[];
        };
        ReallocationPreviewResponse: {
            /** Format: int32 */
            floor?: number;
            rooms?: components["schemas"]["RoomSummary"][];
            allocations?: components["schemas"]["CompartmentAllocationView"][];
            /** Format: int32 */
            chillCompartmentCount?: number;
        };
        RoomSummary: {
            /** Format: uuid */
            roomId?: string;
            roomNumber?: string;
            roomType?: string;
            /** Format: int32 */
            floor?: number;
        };
        CompartmentAllocationInput: {
            /** Format: uuid */
            compartmentId: string;
            roomIds: string[];
        };
        ReallocationApplyRequest: {
            /** Format: int32 */
            floor?: number;
            allocations: components["schemas"]["CompartmentAllocationInput"][];
        };
        ReallocationApplyResponse: {
            /** Format: int32 */
            floor?: number;
            /** Format: int32 */
            affectedCompartments?: number;
            /** Format: int32 */
            releasedAssignments?: number;
            /** Format: int32 */
            createdAssignments?: number;
            /** Format: date-time */
            appliedAt?: string;
        };
        UpdateNotificationPreferenceRequest: {
            enabled: boolean;
            allowBackground: boolean;
        };
        NotificationPreferenceItemResponse: {
            kindCode?: string;
            displayName?: string;
            description?: string;
            enabled?: boolean;
            allowBackground?: boolean;
        };
        UpdateItemRequest: {
            name?: string;
            /** Format: date */
            expiryDate?: string;
            /** Format: int32 */
            quantity?: number;
            unitCode?: string;
            /** Format: date-time */
            removedAt?: string;
        };
        InspectionActionMutationRequest: {
            /** Format: int64 */
            actionId?: number;
            /** Format: uuid */
            bundleId?: string;
            /** Format: uuid */
            itemId?: string;
            action: string;
            note?: string;
        };
        UpdateInspectionSessionRequest: {
            notes?: string;
            mutations?: components["schemas"]["InspectionActionMutationRequest"][];
            deleteActionIds?: number[];
        };
        UpdateInspectionScheduleRequest: {
            /** Format: date-time */
            scheduledAt?: string;
            title?: string;
            notes?: string;
            status?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: uuid */
            inspectionSessionId?: string;
            detachInspectionSession?: boolean;
            /** Format: uuid */
            fridgeCompartmentId?: string;
        };
        UpdateBundleRequest: {
            bundleName?: string;
            memo?: string;
            /** Format: date-time */
            removedAt?: string;
        };
        UpdateUserStatusRequest: {
            status: string;
            reason: string;
        };
        UpdateCompartmentConfigRequest: {
            /** Format: int32 */
            maxBundleCount?: number;
            status?: string;
        };
        FridgeSlotResponse: {
            /** Format: uuid */
            slotId: string;
            /**
             * Format: uuid
             * @description Slot이 소속된 물리적 냉장고의 영속 식별자
             */
            fridgeId: string;
            /**
             * Format: int32
             * @description 필터와 정렬에 사용하는 층 번호
             */
            floorNo: number;
            /** @description 사용자에게 표시하는 층 코드 */
            floorCode: string;
            compartmentType: string;
            resourceStatus: string;
            /** Format: int32 */
            capacity: number;
            /** @description 관리자가 지정하며 사용자가 칸을 구분할 때 사용하는 필수 표시명. A칸, 1번 칸, 상단 냉장칸 등 운영 환경에 맞는 표기를 담으며 영속 식별이나 관계 키로 사용하지 않는다. */
            displayName: string;
            /** Format: int32 */
            occupiedCount: number;
        };
        HealthResponse: {
            status?: string;
            timestamp?: string;
        };
        NotificationItemResponse: {
            /** Format: uuid */
            id?: string;
            kindCode?: string;
            title?: string;
            body?: string;
            state?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            readAt?: string;
            /** Format: date-time */
            ttlAt?: string;
            /** Format: uuid */
            correlationId?: string;
            metadata?: {
                [key: string]: Record<string, never>;
            };
        };
        NotificationListResponse: {
            items?: components["schemas"]["NotificationItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            unreadCount?: number;
        };
        NotificationPreferenceResponse: {
            items?: components["schemas"]["NotificationPreferenceItemResponse"][];
        };
        FridgeSlotListResponse: {
            items: components["schemas"]["FridgeSlotResponse"][];
            /**
             * Format: int64
             * @description 권한 범위와 요청 필터를 모두 적용한 전체 결과 수
             */
            totalCount: number;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /**
             * Format: int32
             * @description 필터 적용 후 totalCount와 요청 size로 계산한 전체 페이지 수
             */
            totalPages: number;
        };
        BundleListResponse: {
            items?: components["schemas"]["FridgeBundleSummaryResponse"][];
            /** Format: int64 */
            totalCount?: number;
        };
        FridgeBundleSummaryResponse: {
            /**
             * Format: uuid
             * @description 포장의 UUID 영속 식별자. 라벨 번호와 구분하며 API 및 이력 연결에 사용한다.
             */
            bundleId?: string;
            /** Format: uuid */
            slotId?: string;
            /** Format: int32 */
            slotIndex?: number;
            slotLabel?: string;
            /**
             * Format: int32
             * @description 동일 Slot 안에서 발급되는 사용자용 라벨 번호. 화면에서는 3자리로 표시한다.
             */
            labelNumber?: number;
            /** @description 현재 slotLabel과 3자리 labelNumber를 조합한 표시값. 영속 식별자나 유일성 기준으로 사용하지 않는다. */
            labelDisplay?: string;
            bundleName?: string;
            memo?: string;
            /** Format: uuid */
            ownerUserId?: string;
            ownerDisplayName?: string;
            ownerRoomNumber?: string;
            status?: string;
            freshness?: string;
            /** Format: int32 */
            itemCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            removedAt?: string;
            items?: components["schemas"]["FridgeItemResponse"][];
        };
        AdminUsersResponse: {
            items?: components["schemas"]["User"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            availableFloors?: number[];
        };
        PenaltyRecord: {
            module?: string;
            source?: string;
            /** Format: int32 */
            points?: number;
            reason?: string;
            issuedAt?: string;
        };
        User: {
            id?: string;
            name?: string;
            room?: string;
            /** Format: int32 */
            floor?: number;
            roomCode?: string;
            /** Format: int32 */
            personalNo?: number;
            /** @description 계정 자체에 부여된 권한 */
            accountAuthorities?: string[];
            isResident?: boolean;
            isFridgeManager?: boolean;
            status?: string;
            lastLogin?: string;
            /** Format: int32 */
            penalties?: number;
            penaltyRecords?: components["schemas"]["PenaltyRecord"][];
        };
        AdminPoliciesResponse: {
            notification?: components["schemas"]["NotificationPolicy"];
            penalty?: components["schemas"]["PenaltyPolicy"];
        };
        AdminFridgeOwnershipIssuesResponse: {
            items?: components["schemas"]["Issue"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        Issue: {
            /** Format: uuid */
            bundleId?: string;
            bundleName?: string;
            /** Format: int32 */
            labelNumber?: number;
            /** Format: uuid */
            ownerUserId?: string;
            ownerName?: string;
            ownerLoginId?: string;
            /** Format: uuid */
            roomId?: string;
            roomNumber?: string;
            /** Format: int32 */
            roomFloor?: number;
            /** Format: int32 */
            personalNo?: number;
            /** Format: uuid */
            fridgeCompartmentId?: string;
            /** Format: int32 */
            slotIndex?: number;
            compartmentType?: string;
            /** Format: int32 */
            fridgeFloorNo?: number;
            fridgeDisplayName?: string;
            issueType?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AdminDashboardResponse: {
            summary?: components["schemas"]["SummaryCard"][];
            timeline?: components["schemas"]["TimelineEvent"][];
            quickActions?: components["schemas"]["QuickAction"][];
        };
        QuickAction: {
            id?: string;
            title?: string;
            description?: string;
            href?: string;
            icon?: string;
        };
        SummaryCard: {
            id?: string;
            label?: string;
            value?: string;
            description?: string;
        };
        TimelineEvent: {
            id?: string;
            time?: string;
            title?: string;
            detail?: string;
        };
    };
    responses: {
        /** @description CSRF 토큰이 누락·불일치·만료되어 요청 검증에 실패함. 세부 원인은 외부에서 구분하지 않는다. */
        CsrfInvalidResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "title": "요청 검증 실패",
                 *       "status": 403,
                 *       "detail": "보안 토큰이 유효하지 않습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.",
                 *       "code": "CSRF_INVALID"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description 로그인이 금지된 이유를 안정적인 오류 코드로 구분한다. ACCOUNT_INACTIVE는 올바른 자격 증명의 비활성 계정, CSRF_INVALID는 CSRF 토큰 누락·불일치·만료에 사용한다. */
        LoginForbiddenResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description 아이디가 존재하지 않거나 비밀번호가 일치하지 않음. 두 원인을 외부 응답에서 구분하지 않는다. */
        InvalidCredentialsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "title": "인증 실패",
                 *       "status": 401,
                 *       "detail": "아이디 또는 비밀번호가 올바르지 않습니다.",
                 *       "code": "AUTH_INVALID_CREDENTIALS"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Error response in ProblemDetail format */
        ProblemDetailResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminPoliciesResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updatePolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdminPoliciesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                slotId?: string;
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"][];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartInspectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    submitSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SubmitInspectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    recordActions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectionActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    listSchedules: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
                floor?: number;
                compartmentId?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"][];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInspectionScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getBundles: {
        parameters: {
            query?: {
                slotId?: string;
                owner?: string;
                status?: string;
                search?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BundleListResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    createBundle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBundleRequest"];
            };
        };
        responses: {
            /** @description 포장 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateBundleResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            /** @description 허용량 초과 – detail 값이 `CAPACITY_EXCEEDED` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CreateBundleResponse"];
                };
            };
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeItemResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 완료. 응답 본문은 없다. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfInvalidResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공. 응답의 Set-Cookie로 HttpOnly 세션 쿠키를 발급한다. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["InvalidCredentialsResponse"];
            403: components["responses"]["LoginForbiddenResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    seedFridgeDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초기화 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeedResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeedResponse"];
                };
            };
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReallocationPreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReallocationPreviewResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReallocationApplyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReallocationApplyResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updatePreference: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kindCode: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationPreferenceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationPreferenceItemResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeItemResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    cancelSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInspectionSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scheduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInspectionScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeBundleResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    deleteBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updateBundle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bundleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBundleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeBundleResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updateUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    updateCompartment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compartmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCompartmentConfigRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            /** @description 대상 칸 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            /** @description 검사 세션 진행 중 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            /** @description 현재 활성 포장 수보다 낮은 용량으로 설정 시 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"];
                };
            };
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getNotifications: {
        parameters: {
            query?: {
                state?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationListResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NotificationPreferenceResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getSlots: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FridgeSlotListResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getActiveSession: {
        parameters: {
            query?: {
                floor?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getNextSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionScheduleResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getUsers: {
        parameters: {
            query?: {
                status?: string;
                floor?: string;
                fridgeManagerOnly?: boolean;
                search?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminUsersResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getFridgeOwnershipIssues: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                ownerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminFridgeOwnershipIssuesResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    listCompartments: {
        parameters: {
            query?: {
                floor?: number;
                view?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"][];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            /** @description 관리자 권한 필요 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FridgeSlotResponse"][];
                };
            };
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getDeletedBundles: {
        parameters: {
            query?: {
                since?: string;
                slotId?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BundleListResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminDashboardResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    deleteAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                actionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
    resendInspectionNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InspectionSessionResponse"];
                };
            };
            400: components["responses"]["ProblemDetailResponse"];
            401: components["responses"]["ProblemDetailResponse"];
            403: components["responses"]["ProblemDetailResponse"];
            404: components["responses"]["ProblemDetailResponse"];
            409: components["responses"]["ProblemDetailResponse"];
            422: components["responses"]["ProblemDetailResponse"];
            500: components["responses"]["ProblemDetailResponse"];
        };
    };
}
